### ISSUE TITLE
Parsing cuts the numbers

### ISSUE THREAD

**Issue by MrZnake** [adharmawan/vscode-json#6]
The problem occurs both during use `Uglify` and `Beautify` on json file with large numbers.

![error](https://user-images.githubusercontent.com/20782978/55642733-9de01300-57d1-11e9-9c3e-c26cc7eccde5.gif)

Starting values: `{"id1":365247355169013770,"id2":367559095164600330}`
Result after use:`{"id1":365247355169013760,"id2":367559095164600300}`

**Extension version**: `1.4.2`

**Comment by ups91** [comment]
https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin
The real safe MAX number is 9007199254740991 ( Number.MAX_SAFE_INTEGER )

**Comment by andyyaldoo** [comment]
Limitation of `JSON.parse()`
https://stackoverflow.com/questions/38070943/number-value-changes-on-json-parse. 

Basically I need to convert it to `String` and then parse it and then convert it back to `Number`

Or just use https://github.com/sidorares/json-bigint :)

**Comment by andyyaldoo** [comment]
I'll try to work on it this weekend

**Comment by adharmawan** [comment]
Fixed by #7
